version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3342:3342
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    logging:
      driver: none

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    logging:
      driver: none

  server:
    image: nginx
    container_name: nginx
    ports:
      - 8888:80
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: none

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
    logging:
      driver: none
